# This file was generated by GoReleaser. DO NOT EDIT.
cask "seshare" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "b693dc6f3e614b40fca9a6c703c1f30430700de02a01d2ef4dbe044676d3436c"
      url "https://github.com/cursoroid/seshare/releases/download/v#{version}/seshare_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "ad6ddc5e6cfaef85f717241df67f60594566e9477a78be45e81ef9adad278dbd"
      url "https://github.com/cursoroid/seshare/releases/download/v#{version}/seshare_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "119ea9ba257faf7655ced968d82c2d1c2c77aa211345347568b376fced5b2f3c"
      url "https://github.com/cursoroid/seshare/releases/download/v#{version}/seshare_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "8cdec0ab7c92ec7d5439d9ad270dd441e91dcd7194b7453f97d68bbbdfbe4ac2"
      url "https://github.com/cursoroid/seshare/releases/download/v#{version}/seshare_linux_arm64.tar.gz"
    end
  end

  name "seshare"
  desc "Share Claude Code sessions peer-to-peer over croc"
  homepage "https://github.com/cursoroid/seshare"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "seshare"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/seshare"]
    end
  end

  # No zap stanza required

end
