# This file was generated by GoReleaser. DO NOT EDIT.
cask "seshare" do
  version "0.2.1"

  on_macos do
    on_intel do
      sha256 "e13b05dd38edb2635cc11b3d28f03472dca23871e66cd9509177648bed47f57f"
      url "https://github.com/cursoroid/seshare/releases/download/v#{version}/seshare_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "936f69faf7c35e79d9f8f3b632dbcc500f709fe3b999c0582e06c331d4dee6e4"
      url "https://github.com/cursoroid/seshare/releases/download/v#{version}/seshare_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "f8415e6252d2b3a270e3b07b62f34f1339fb5db207c52e51b5b2290278d8cc04"
      url "https://github.com/cursoroid/seshare/releases/download/v#{version}/seshare_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "17062a02ef737119d2eeb549fd81eca773c8d54a08e3162ba7b4811c6408c4d6"
      url "https://github.com/cursoroid/seshare/releases/download/v#{version}/seshare_linux_arm64.tar.gz"
    end
  end

  name "seshare"
  desc "Share Claude Code sessions peer-to-peer over croc"
  homepage "https://github.com/cursoroid/seshare"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "seshare"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/seshare"]
    end
  end

  # No zap stanza required

end
