# This file was generated by GoReleaser. DO NOT EDIT.
cask "seshare" do
  version "0.2.0"

  on_macos do
    on_intel do
      sha256 "a1674e2a5023e0e589dc8fc7ba4bf9f1a44476eeb0593090967e64631ed9a8bc"
      url "https://github.com/cursoroid/seshare/releases/download/v#{version}/seshare_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "664390f324a14f8ca93214f5ab11decd1b6587fa4da7d247f3f0ba21f0daeb13"
      url "https://github.com/cursoroid/seshare/releases/download/v#{version}/seshare_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "5ec285c1b8d5da3c65f6b7f81573d74d5d26b4d8e44724c8ee2ecfb8f46f0eef"
      url "https://github.com/cursoroid/seshare/releases/download/v#{version}/seshare_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "3b7fb7419cb4df98d493d35845131abe55286ba3ffbc72e808e3b4768534a4bd"
      url "https://github.com/cursoroid/seshare/releases/download/v#{version}/seshare_linux_arm64.tar.gz"
    end
  end

  name "seshare"
  desc "Share Claude Code sessions peer-to-peer over croc"
  homepage "https://github.com/cursoroid/seshare"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "seshare"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/seshare"]
    end
  end

  # No zap stanza required

end
